site_name: Happyculteur Wiki
site_description: Wiki for the Happyculteur web based free and open source application
site_author: Alexandre Kervadec
site_url: https://wiki.app.happyculteur.co

repo_name: happyculteur/wiki
repo_url: https://github.com/happyculteur/wiki

copyright: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>

theme:
  name: 'material'
  palette:
    primary: 'yellow'
    accent: 'yellow'
  logo:
    icon: home
  feature:
    tabs: false

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

pages:
  - Home: index.md
  - Roadmap:
    - Setting-up: roadmap/setting-up.md
    - Register form: roadmap/register_form.md
    - MVP: roadmap/mvp.md
  - Architecture:
    - General architecture: architecture/general/general.md
    - Frontend:
      - Data structure:
        - Structures: architecture/frontend/data_structure.md
        - Beekeeper: architecture/frontend/data_structure_beekeeper.md
        - Individual: architecture/frontend/data_structure_individual.md
        - Space: architecture/frontend/data_structure_space.md
    - Backend:
      - Data structure:
        - Structures: architecture/backend/data_structure.md
        - Beekeeper: architecture/backend/data_structure_beekeeper.md
        - Individual: architecture/backend/data_structure_individual.md
        - Space: architecture/backend/data_structure_space.md
